spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chat
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: thangnguyen12112003@gmail.com
    password: hbax snwz nfqk qmrs    # Mật khẩu ứng dụng của Gmail
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        transport.protocol: smtp
        debug: true # Tùy chọn: Thêm để theo dõi chi tiết quá trình gửi email

cloudinary:
  cloud-name: dqfmh4yif
  api-key: 795551377454287
  api-secret: gM2_ZF5InTRzYT9imLH6jURcNQ4

twilio:
  accountSid: ACe702fa96fb36ac1469d46978db4c47b2
  authToken: dd1b1896b30f2cdc9da93921af5f67a6
  phoneNumber: +12028313502

cscApi:
  key: MGZMRlZLbkZ0SmNiOGkxQzBlREFLYjBKdlZZU1BnRmlRbGI3N2lvVg==

logging:
  level:
    root: INFO
    org.springframework.mail: DEBUG
    org.springframework.web: DEBUG

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 604800000 # 7 days
      refresh-token:
        expiration: 604800000 # 7 days
